# fly.toml app configuration file generated for scrum-poker-nine on 2023-07-07T11:39:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "scrum-poker-nine"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
